### ISSUE TITLE
header html + css

### ISSUE THREAD

**Issue by mgiraldo** [NYPL/pd-visualization#1]
the header html should be:

``` html
    <a href="//nypl.org" target="_blank" title="open nypl.org in a new window"><span class="lion">The New York Public Library</span></a> A <a href="//publicdomain.nypl.org">public domain remix</a> by Brian Foo of <a href="http://labs.nypl.org">NYPL Labs</a>, using the <a href="https://github.com/NYPL-publicdomain/data-and-utilities">data released by NYPL</a>. <a href="//github.com/nypl-publicdomain/pd-visualization">View source code</a>.
```

(add a link on name if desired)

the corresponding css to the `.lion` element is:

``` css
.lion {
  display: inline-block;
  background: transparent url(../images/lion-rev.png) no-repeat;
  width: 30px;
  height: 30px;
  margin-right: 10px;
  font-size: 1px;
  color: #000; /* this should be the background color of the parent element */
  vertical-align: middle;
}
```

the image for the lion is (white on white seems invisible here but it's there):
![lion-rev](https://cloud.githubusercontent.com/assets/133020/11936743/d4e0379c-a7dd-11e5-8161-01b8d5f3ed82.png)
